image:
  file: .gitpod.Dockerfile

vscode:
    extensions:
       - panekj.powershell
       - ms-vscode.azure-account
       - ms-vscode.azurecli
       - ms-azuretools.vscode-docker
       - akosyakov.gitpod-monitor

#        - eamodio.gitlens
